apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-bench-metrics
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kube-metrics-wrapper.name" . }}-cluster
rules:
- apiGroups: [""] 
  resources: ["pods","nodes"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-bench-metrics-role-binding
subjects:
- kind: ServiceAccount
  name: kube-bench-metrics
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole 
  name: {{ include "kube-metrics-wrapper.name" . }}-cluster
  apiGroup: rbac.authorization.k8s.io
