{{ if .Values.prometheus.enabled  }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: {{ include "kube-metrics-wrapper.name" . }}
    release: prometheus-operator
  name: {{ include "kube-metrics-wrapper.name" . }}-monitoring
  {{- if .Values.prometheus.namespace }}
  namespace: {{ .Values.prometheus.namespace }}
  {{- end }}
spec:
  endpoints:
  - port: http
    interval: 30s
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kube-metrics-wrapper.name" . }}
{{- end }}
