{
 "title": "CIS BenchMarking",
 "description": "Dashboard to show CIS compliance for a cluster",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "hostname", "label": "hostname" }
  ]
 },
 "panels": [
  {
   "title": "Scored Checks Passed",
   "type": "singlestat",
   "description": "Automated Scored Checks Passed",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(cis_results{hostname=~\"$hostname\",scored=\"true\",type=\"automated\",status=\"PASS\"})",
     "legendFormat": "Checks Passed"
    },
    { "legendFormat": "Total Checks Performed" }
   ]
  },
  {
   "title": "Scored Checks Run",
   "type": "singlestat",
   "description": "Total Number of Automated Scored Checks Run",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(cis_results{hostname=~\"$hostname\",scored=\"true\",type=\"automated\"})"
    }
   ]
  },
  {
   "title": "CIS Benchmarking Results",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "cis_results{hostname=~\"$hostname\"}"
    }
   ]
  }
 ]
}