{
 "title": "CIS Kubernetes Benchmark",
 "description": "Dashboard to show CIS compliance for a cluster",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(cis_results,cluster)"
   },
   {
    "name": "hostname",
    "label": "hostname",
    "query": "label_values(cis_results,hostname)"
   }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "\n# CIS benchmarking tests, implemented by kube-bench\n\nThese tests are specified by CIS and implemented by kube-bench, see more information (such as descriptions of the different tests) about CIS [here](https://www.cisecurity.org/benchmark/kubernetes/) and kube-bench [here](https://github.com/aquasecurity/kube-bench).\n\nAutomatic vs manual tests: CIS have determined that some tests can be run automatically, kube-bench have aditionally turned some manual tests into automatic ones. In this dashboard the manual tests (as per kube-bench) are only included in the table at the bottom.\n\nScored vs non-scored: scored tests are the test CIS chose as automatic, non-scored test are the manual tests that kube-bench made automatic. Non-scored might not fit as many kubernetes setups and are thus only classified as warnings if they fail.\n\nPlease see [CIS 1.23 Self-Assessment Guide](https://docs.rke2.io/security/cis_self_assessment123) for detailed descriptions and remediations for failing tests."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Checks Passed",
   "type": "gauge",
   "description": "All Automated Checks Passed",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(cis_results{cluster=~\"$cluster\",hostname=~\"$hostname\",type=\"automated\",status=\"PASS\"})/count(cis_results{cluster=~\"$cluster\",hostname=~\"$hostname\",type=\"automated\"})",
     "legendFormat": "Checks Passed"
    }
   ]
  },
  {
   "title": "Scored Checks Passed",
   "type": "gauge",
   "description": "Automated Scored Checks Passed",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(cis_results{cluster=~\"$cluster\",hostname=~\"$hostname\",scored=\"true\",type=\"automated\",status=\"PASS\"})/count(cis_results{cluster=~\"$cluster\",hostname=~\"$hostname\",scored=\"true\",type=\"automated\"})",
     "legendFormat": "Checks Passed"
    }
   ]
  },
  {
   "title": "Non-Scored Checks Passed",
   "type": "gauge",
   "description": "Automated Non-Scored Checks Passed",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(cis_results{cluster=~\"$cluster\",hostname=~\"$hostname\",scored=\"false\",type=\"automated\",status=\"PASS\"})/count(cis_results{cluster=~\"$cluster\",hostname=~\"$hostname\",scored=\"false\",type=\"automated\"})",
     "legendFormat": "Checks Passed"
    }
   ]
  },
  {
   "title": "Total Checks Passed",
   "type": "stat",
   "description": "All Automated Checks Passed",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(cis_results{cluster=~\"$cluster\",hostname=~\"$hostname\",type=\"automated\",status=\"PASS\"})",
     "legendFormat": "Checks Passed"
    }
   ]
  },
  {
   "title": "Total Checks Run",
   "type": "stat",
   "description": "Total Number of All Automated Checks Run",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(cis_results{cluster=~\"$cluster\",hostname=~\"$hostname\",type=\"automated\"})"
    }
   ]
  },
  {
   "title": "Scored Checks Passed",
   "type": "stat",
   "description": "Automated Scored Checks Passed",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(cis_results{cluster=~\"$cluster\",hostname=~\"$hostname\",scored=\"true\",type=\"automated\",status=\"PASS\"})"
    }
   ]
  },
  {
   "title": "Scored Checks Run",
   "type": "stat",
   "description": "Total Number of Automated Scored Checks Run",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(cis_results{cluster=~\"$cluster\",hostname=~\"$hostname\",scored=\"true\",type=\"automated\"})"
    }
   ]
  },
  {
   "title": "Non-Scored Checks Passed",
   "type": "stat",
   "description": "Automated Non-Scored Checks Passed",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(cis_results{cluster=~\"$cluster\",hostname=~\"$hostname\",scored=\"false\",type=\"automated\",status=\"PASS\"})",
     "legendFormat": "Checks Passed"
    }
   ]
  },
  {
   "title": "Non-Scored Checks Run",
   "type": "stat",
   "description": "Total Number of Automated Non-Scored Checks Run",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(cis_results{cluster=~\"$cluster\",hostname=~\"$hostname\",scored=\"false\",type=\"automated\"})"
    }
   ]
  },
  {
   "title": "CIS Benchmarking Results",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "cis_results{cluster=~\"$cluster\",hostname=~\"$hostname\"}"
    }
   ]
  }
 ]
}